### ISSUE TITLE
[IMP] toj-1001_reverse_root. Изменить название переменных 

### ISSUE THREAD

**Issue by galkin-online** [Alexander-V-Galkin/I_Learn_Rust#4]
1. Исходные данные, которые считываются в виде строки и затем парсятся, переименовать из stdin в input
https://github.com/Alexander-V-Galkin/I_Learn_Rust/blob/c2f0c4dbd4449bc78a03c7202313bd3bb6ab3140/Timus_Online_Judge/toj-1001_reverse_root/src/main.rs#L4

2. Вектор исходных данных, полученных после парсинга переименовать из input в integers
https://github.com/Alexander-V-Galkin/I_Learn_Rust/blob/c2f0c4dbd4449bc78a03c7202313bd3bb6ab3140/Timus_Online_Judge/toj-1001_reverse_root/src/main.rs#L5

**Comment by Alexander-V-Galkin** [comment]
Решено https://github.com/Alexander-V-Galkin/I_Learn_Rust/commit/7128617879e4eb891a634995dedae0aca7714437

**Comment by galkin-online** [comment]
Решено
https://github.com/Alexander-V-Galkin/I_Learn_Rust/commit/7128617879e4eb891a634995dedae0aca7714437
